### ISSUE TITLE
List of events

### ISSUE THREAD

**Issue by Han-90** [Han-90/capstone-project#15]
As a user 
I want to see a list of all events
so that I know what's coming up

## AC

*Events are displayed below the form on the Event page
*Events are displayed in a list
*Single Event displays the name, location, date.

## Tasks

* create new branch and Component
* save multiple events in state 
* Render list of events

**Comment by JessicaLoers** [comment]
**Hi @Han-90** 👋
well done.  Just a few suggestions. 

**AC** --> Describe it a little more specifically. e.g :
- Events are displayed below the form on the Event page
- Events are displayed in a list
- Single Event displays the name, location, date. 

**Tasks** --> Describe it a little more specifically. e.g :
- create new branch and Component
- save multiple events --> do you mean **_Save events in state_**
- show events in list -->  **_Render list of events_**
